const STEP_META = {
  personal: { title: "مشخصات فردی", kicker: "هویت و اطلاعات تماس" },
  marriage: { title: "سوابق ازدواج", kicker: "وضعیت خانوادگی" },
  military: { title: "وضعیت نظام وظیفه", kicker: "خدمت و معافیت" },
  education: { title: "سوابق تحصیلی", kicker: "مدارک دانشگاهی و حوزوی" },
  employment: { title: "سوابق شغلی", kicker: "تجربه و محل‌های کار" },
  accommodation: { title: "اقامت و اسکان", kicker: "خوابگاه و پانسیون" },
  passport: { title: "سوابق گذرنامه", kicker: "ارتباطات و سوابق" },
  foreign_contacts: { title: "ارتباطات خارج از کشور", kicker: "مکاتبه، تماس و ارتباطات مجازی" },
  screening_history: { title: "سوابق گزینش", kicker: "پرونده‌های قبلی" },
  veteran: { title: "سوابق ایثارگری", kicker: "رزمندگی، جانبازی و شهادت" },
  travel: { title: "سفر و اقامت خارج از کشور", kicker: "مسافرت و اقامت" },
  legal_incidents: { title: "سوابق قضایی و انتظامی", kicker: "احضار، بازداشت و دستگیری" },
  migration: { title: "مهاجرت و پناهندگی", kicker: "وضعیت مهاجرت و بازگشت" },
  affiliations: { title: "ارتباط و همکاری", kicker: "اشخاص، تشکل‌ها و گروه‌ها" },
  addiction: { title: "سوابق اعتیاد", kicker: "اطلاعات اعلامی" },
  foreign_company_relations: { title: "شرکت‌ها و مؤسسات خارجی", kicker: "همکاری و اشتغال" },
  embassy_relations: { title: "سفارتخانه و کنسولگری", kicker: "اشتغال و ارتباطات" },
  exit_restrictions: { title: "ممنوع‌الخروجی", kicker: "سوابق و نتایج" },
  activities: { title: "فعالیت‌های اجتماعی و فرهنگی", kicker: "سیاسی، فرهنگی، جهادی و اجتماعی" },
  weapons: { title: "سوابق سلاح", kicker: "سلاح و مجوز" },
  family: { title: "خانواده", kicker: "والدین، خواهر و برادر، همسر و فرزندان" },
  social_relations: { title: "معرفین، دوستان و همسایگان", kicker: "منابع شناخت" },
  residence: { title: "سوابق سکونت ده سال اخیر", kicker: "نشانی‌های محل سکونت" },
  additional: { title: "توضیحات تکمیلی", kicker: "موارد و سوابق تکمیلی" },
  declaration: { title: "تعهد نهایی", kicker: "تأیید و ثبت نهایی پرونده" },
  documents: { title: "مدارک", kicker: "بارگذاری مستندات" },
  review: { title: "مرور نهایی", kicker: "کنترل اطلاعات پیش از ثبت" },
};

const RECORDS = {
  education: [
    { key: "degree_level", label: "مقطع تحصیلی / سطح", type: "text", required: true },
    { key: "institution_name", label: "نام دانشگاه / حوزه", type: "text", required: true },
    { key: "institution_type", label: "نوع دانشگاه", type: "text" },
    { key: "field_of_study", label: "رشته / گرایش", type: "text", required: true },
    { key: "gpa", label: "معدل", type: "number" },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "is_current", label: "در حال تحصیل هستم", type: "boolean" },
    { key: "address_line", label: "نشانی محل تحصیل", type: "textarea", full: true },
    { key: "phone", label: "تلفن محل تحصیل", type: "text" },
  ],
  employment: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "متقاضی" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "organization_name", label: "اداره / محل کار", type: "text", required: true },
    { key: "membership_type", label: "نوع عضویت (رسمی، قراردادی و ...)", type: "text" },
    { key: "position", label: "سمت و شغل", type: "text", required: true },
    { key: "start_date", label: "تاریخ به‌کارگیری", type: "date", required: true },
    { key: "end_date", label: "تاریخ قطع همکاری", type: "date" },
    { key: "termination_reason", label: "علت ترک خدمت (استعفا، بازنشستگی و ...)", type: "textarea", full: true, visibleWhen: (record) => Boolean(record.end_date) },
    { key: "work_address", label: "نشانی محل کار", type: "textarea", full: true },
    { key: "manager_name", label: "نام مسئول", type: "text" },
    { key: "manager_phone", label: "تلفن مسئول", type: "text" },
    { key: "work_phone", label: "تلفن محل کار", type: "text" },
  ],
  passport: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "متقاضی" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "passport_type", label: "نوع گذرنامه", type: "text", required: true },
    { key: "passport_number", label: "شماره گذرنامه", type: "text", required: true },
    { key: "issue_date", label: "تاریخ صدور", type: "date" },
    { key: "expiry_date", label: "تاریخ انقضا", type: "date" },
    { key: "issue_location", label: "محل دریافت", type: "text" },
    { key: "notes", label: "ملاحظات", type: "textarea", full: true },
  ],
  foreign_contacts: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "country_name", label: "کشور", type: "text", required: true },
    { key: "entity_name", label: "نام فرد / مؤسسه", type: "text", required: true },
    { key: "contact_type", label: "نوع ارتباط", type: "text", required: true },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "reason", label: "علت و موضوع", type: "textarea", full: true },
    { key: "result", label: "نتیجه ارتباط", type: "textarea", full: true },
    { key: "notes", label: "ملاحظات", type: "textarea", full: true },
  ],
  accommodation: [
    { key: "name", label: "نام خوابگاه / پانسیون", type: "text", required: true },
    { key: "start_date", label: "تاریخ شروع اسکان", type: "date", required: true },
    { key: "end_date", label: "تاریخ پایان اسکان", type: "date" },
    { key: "address_line", label: "آدرس خوابگاه", type: "textarea", full: true },
    { key: "day_manager_name", label: "مسئول روز", type: "text" },
    { key: "day_manager_phone", label: "تلفن مسئول روز", type: "text" },
    { key: "night_manager_name", label: "مسئول شب", type: "text" },
    { key: "night_manager_phone", label: "تلفن مسئول شب", type: "text" },
  ],
  screening_history: [
    { key: "organization_name", label: "نام سازمان / اداره", type: "text", required: true },
    { key: "screening_date", label: "تاریخ گزینش", type: "date" },
    { key: "result", label: "نتیجه گزینش", type: "text", required: true },
    { key: "rejection_reason", label: "علت عدم پذیرش", type: "textarea", full: true, visibleWhen: (record) => /رد|عدم پذیرش|نپذیرفته/.test(record.result || "") },
    { key: "address", label: "نشانی محل گزینش", type: "textarea", full: true },
    { key: "phone", label: "تلفن محل گزینش", type: "text" },
  ],
  veteran: [
    { key: "beneficiary_type", label: "این سابقه مربوط به", type: "select", required: true, options: [{ value: "APPLICANT", label: "خود متقاضی" }, { value: "RELATIVE", label: "یکی از بستگان" }] },
    { key: "relative_relation", label: "نسبت با متقاضی", type: "text" },
    { key: "relative_first_name", label: "نام شخص ایثارگر", type: "text" },
    { key: "relative_last_name", label: "نام خانوادگی شخص ایثارگر", type: "text" },
    { key: "veteran_type", label: "نوع ایثارگری", type: "select", required: true, options: ["رزمندگی", "جانبازی", "آزادگی", "شهادت"] },
    { key: "percentage", label: "درصد ایثارگری", type: "number" },
    { key: "occurrence_date", label: "تاریخ وقوع / اعزام", type: "date" },
    { key: "location", label: "محل وقوع / اعزام", type: "text" },
    { key: "issuing_authority", label: "اعزام‌کننده / مرجع", type: "text" },
    { key: "duration", label: "مدت ایثارگری", type: "text" },
    { key: "notes", label: "توضیحات", type: "textarea", full: true },
  ],
  travel: [
    { key: "beneficiary_type", label: "این سابقه مربوط به", type: "select", required: true, options: [
      { value: "APPLICANT", label: "خود متقاضی" },
      { value: "SPOUSE", label: "همسر" },
      { value: "RELATIVE", label: "یکی از بستگان" },
    ] },
    { key: "relative_relation", label: "نسبت با متقاضی", type: "select", options: ["پدر", "مادر", "همسر", "فرزند", "برادر", "خواهر", "پدربزرگ", "مادربزرگ", "نوه", "عمو", "عمه", "دایی", "خاله", "سایر"], visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_first_name", label: "نام شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_last_name", label: "نام خانوادگی شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "country_name", label: "کشور خارجی", type: "text", required: true },
    { key: "travel_type", label: "نوع مسافرت / اقامت", type: "text", required: true },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "duration", label: "مدت مسافرت / اقامت", type: "text" },
    { key: "exit_border", label: "مرز خروجی", type: "select", options: [
      "فرودگاه بین‌المللی امام خمینی",
      "فرودگاه شهید هاشمی‌نژاد مشهد",
      "فرودگاه شهید دستغیب شیراز",
      "فرودگاه شهید مدنی تبریز",
      "مرز بازرگان",
      "مرز رازی",
      "مرز سرو",
      "مرز تمرچین",
      "مرز باشماق",
      "مرز آستارا",
      "مرز بیله‌سوار",
      "مرز شلمچه",
      "مرز چذابه",
      "مرز دریایی بندرعباس",
      "سایر",
    ] },
    { key: "passport_number", label: "شماره گذرنامه", type: "text" },
    { key: "transport_type", label: "نحوه سفر", type: "select", options: [
      { value: "air", label: "هوایی" },
      { value: "land", label: "زمینی" },
      { value: "sea", label: "دریایی" },
    ] },
    { key: "stay_type", label: "نوع اقامت", type: "select", options: [
      { value: "permanent", label: "دائم" },
      { value: "temporary", label: "موقت" },
    ] },
    { key: "reason", label: "علت مسافرت / اقامت", type: "textarea", full: true },
    { key: "stay_place", label: "محل اقامت", type: "textarea", full: true },
  ],

  legal_incidents: [
    { key: "beneficiary_type", label: "این سابقه مربوط به", type: "select", required: true, options: [
      { value: "APPLICANT", label: "خود متقاضی" },
      { value: "SPOUSE", label: "همسر" },
      { value: "RELATIVE", label: "یکی از بستگان" },
    ] },
    { key: "relative_relation", label: "نسبت با متقاضی", type: "select", options: ["پدر", "مادر", "همسر", "فرزند", "برادر", "خواهر", "پدربزرگ", "مادربزرگ", "نوه", "عمو", "عمه", "دایی", "خاله", "سایر"], visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_first_name", label: "نام شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_last_name", label: "نام خانوادگی شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "incident_type", label: "نوع سابقه", type: "select", required: true, options: ["احضار", "بازداشت", "دستگیری"] },
    { key: "incident_date", label: "تاریخ", type: "date" },
    { key: "reason", label: "علت", type: "textarea", full: true },
    { key: "location", label: "محل وقوع", type: "text" },
    { key: "authority", label: "مرجع رسیدگی", type: "text" },
    { key: "result", label: "نتیجه رسیدگی", type: "textarea", full: true },
  ],
  migration: [
    { key: "beneficiary_type", label: "این سابقه مربوط به", type: "select", required: true, options: [
      { value: "APPLICANT", label: "خود متقاضی" },
      { value: "SPOUSE", label: "همسر" },
      { value: "RELATIVE", label: "یکی از بستگان" },
    ] },
    { key: "relative_relation", label: "نسبت با متقاضی", type: "select", options: ["پدر", "مادر", "همسر", "فرزند", "برادر", "خواهر", "پدربزرگ", "مادربزرگ", "نوه", "عمو", "عمه", "دایی", "خاله", "سایر"], visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_first_name", label: "نام شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_last_name", label: "نام خانوادگی شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "status", label: "وضعیت", type: "select", required: true, options: ["مهاجر", "پناهنده", "بازگشته"] },
    { key: "reason", label: "علت مهاجرت / پناهندگی / برگشتن", type: "textarea", full: true },
    { key: "current_status", label: "وضعیت فعلی", type: "textarea", full: true },
    { key: "return_date", label: "تاریخ برگشتن", type: "date" },
    { key: "result", label: "نتیجه", type: "textarea", full: true },
  ],
  affiliations: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "entity_name", label: "نام فرد / شرکت", type: "text", required: true },
    { key: "country_name", label: "کشور", type: "text" },
    { key: "relation_type", label: "نوع اشتغال / ارتباط / همکاری", type: "text", required: true },
    { key: "activity_title", label: "عنوان فعالیت / مسئولیت", type: "text" },
    { key: "start_date", label: "از تاریخ", type: "date" },
    { key: "end_date", label: "تا تاریخ", type: "date" },
    { key: "reason", label: "علت اشتغال / ارتباط", type: "textarea", full: true },
    { key: "acquaintance_method", label: "زمینه / نحوه آشنایی", type: "textarea", full: true },
    { key: "termination_reason", label: "علت قطع ارتباط", type: "textarea", full: true, visibleWhen: (record) => Boolean(record.end_date) },
  ],
  addiction: [
    { key: "beneficiary_type", label: "این سابقه مربوط به", type: "select", required: true, options: [
      { value: "APPLICANT", label: "خود متقاضی" },
      { value: "SPOUSE", label: "همسر" },
      { value: "RELATIVE", label: "یکی از بستگان" },
    ] },
    { key: "relative_relation", label: "نسبت با متقاضی", type: "select", options: ["پدر", "مادر", "همسر", "فرزند", "برادر", "خواهر", "پدربزرگ", "مادربزرگ", "نوه", "عمو", "عمه", "دایی", "خاله", "سایر"], visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_first_name", label: "نام شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "relative_last_name", label: "نام خانوادگی شخص", type: "text", visibleWhen: (record) => record?.beneficiary_type === "RELATIVE" },
    { key: "substance_type", label: "ماده مورد استعمال", type: "text", required: true },
    { key: "start_date", label: "از تاریخ", type: "date" },
    { key: "end_date", label: "تا تاریخ", type: "date" },
    { key: "reason", label: "علت", type: "textarea", full: true },
    { key: "convicted", label: "محکومیت داشته‌ام", type: "boolean" },
    { key: "current_status", label: "وضعیت فعلی", type: "textarea", full: true },
  ],
  foreign_company_relations: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "company_name", label: "نام شرکت / مؤسسه", type: "text", required: true },
    { key: "activity_type", label: "نوع فعالیت", type: "text", required: true },
    { key: "country_id", label: "کشور", type: "country", required: true },
    { key: "income_amount", label: "میزان درآمد", type: "number" },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "dependent_country_id", label: "کشور وابستگی", type: "country" },
    { key: "acquaintance_method", label: "نحوه آشنایی", type: "textarea", full: true },
  ],
  embassy_relations: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "country_id", label: "کشور", type: "country", required: true },
    { key: "relation_type", label: "نوع ارتباط", type: "text", required: true },
    { key: "responsibility", label: "مسئولیت", type: "textarea", full: true },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "address", label: "آدرس", type: "textarea", full: true },
    { key: "phone", label: "تلفن", type: "text" },
  ],
  exit_restrictions: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "reference_date", label: "تاریخ مرجع", type: "date" },
    { key: "authority", label: "مرجع ممنوع‌الخروج کننده", type: "text", required: true },
    { key: "reason", label: "علت", type: "textarea", full: true },
    { key: "result", label: "نتیجه", type: "textarea", full: true },
    { key: "lifted_date", label: "تاریخ رفع ممنوعیت", type: "date" },
  ],
  activities: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "organization_name", label: "نام نهاد / تشکل", type: "text", required: true },
    { key: "activity_type", label: "نوع فعالیت", type: "text", required: true },
    { key: "start_date", label: "از تاریخ", type: "date" },
    { key: "end_date", label: "تا تاریخ", type: "date" },
    { key: "responsibility", label: "نوع مسئولیت / فعالیت", type: "textarea", full: true },
    { key: "motivation", label: "علت / انگیزه فعالیت", type: "textarea", full: true },
    { key: "termination_reason", label: "علت ترک فعالیت", type: "textarea", full: true, visibleWhen: (record) => Boolean(record.end_date) },
    { key: "manager_name", label: "نام مسئول", type: "text" },
    { key: "address", label: "نشانی محل فعالیت", type: "textarea", full: true },
    { key: "phone", label: "تلفن", type: "text" },
  ],
  weapons: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "weapon_type", label: "نوع سلاح", type: "text", required: true },
    { key: "model", label: "مدل", type: "text" },
    { key: "caliber", label: "کالیبر", type: "text" },
    { key: "body_number", label: "شماره بدنه", type: "text" },
    { key: "manufacturer_country_id", label: "کشور سازنده", type: "country" },
    { key: "license_authority", label: "مرجع صدور مجوز", type: "text" },
    { key: "license_number", label: "شماره مجوز", type: "text" },
    { key: "license_date", label: "تاریخ مجوز", type: "date" },
    { key: "use_reason", label: "علت استفاده", type: "textarea", full: true },
  ],
};

const FLOW_SECTIONS = [
  ["هویت و اطلاعات پایه", ["personal", "marriage", "military"]],
  ["تحصیل و اشتغال", ["education", "employment", "accommodation"]],
  ["ارتباطات و سوابق", ["foreign_contacts", "screening_history", "veteran", "travel", "legal_incidents", "migration", "passport"]],
  ["ارتباطات تکمیلی", ["affiliations", "addiction", "foreign_company_relations", "embassy_relations", "exit_restrictions", "activities", "weapons"]],
  ["خانواده و منابع شناخت", ["family", "social_relations", "residence"]],
  ["جمع‌بندی", ["additional", "declaration"]],
];

const STATUS = {
  IN_PROGRESS: ["در حال تکمیل", "progress"],
  RETURNED: ["برگشت داده شده", "returned"],
  SUBMITTED: ["ثبت نهایی شده", "submitted"],
  UNDER_REVIEW: ["در حال بررسی", "review"],
  APPROVED: ["تأیید شده", "approved"],
  REJECTED: ["رد شده", "rejected"],
  COMPLETED: ["تکمیل شده", "approved"],
  DRAFT: ["پیش‌نویس", "muted"],
};


const emptyRecord = (fields) => {
  const out = {};
  fields.forEach((field) => {
    out[field.key] = field.type === "boolean" ? null : "";
  });
  return out;
};

const STEP_DESCRIPTIONS = {
  personal: "مشخصات هویتی، اطلاعات تماس و نشانی محل سکونت فعلی را با دقت و مطابق مدارک معتبر تکمیل نمایید.",
  marriage: "سوابق ازدواج خود را به ترتیب ثبت نمایید. وضعیت ازدواج، مشخصات همسر و در صورت وجود، تاریخ و علت پایان ازدواج قبلی را درج کنید.",
  military: "وضعیت نظام وظیفه خود را مشخص کرده و اطلاعات مربوط به خدمت، معافیت، دفترچه و وضعیت غیبت را مطابق واقع ثبت نمایید.",
  education: "اطلاعات تحصیلی خود را به ترتیب از آخرین مدرک تحصیلی دانشگاهی یا حوزوی تا سوابق قبلی ثبت نمایید.",
  employment: "سوابق شغلی خود را از شغل فعلی یا آخرین محل کار به ترتیب ثبت نمایید و مشخصات محل کار، سمت و نوع همکاری را ثبت فرمایید.",
  accommodation: "سوابق اقامت و اسکان خود در خوابگاه، پانسیون یا مراکز اقامتی را در این مرحله ثبت نمایید.",
  passport: "آیا تاکنون گذرنامه دریافت نموده‌اید؟ در صورت دریافت، مشخصات گذرنامه خود را ثبت نمایید و چنانچه متأهل هستید، مشخصات گذرنامه همسر را نیز در صورت وجود درج کنید.",
  foreign_contacts: "چنانچه در گذشته یا حال با خارج از کشور، اعم از طریق مکاتبه، مراسلات، تماس تلفنی یا ارتباطات مجازی، ارتباط داشته‌اید یا دارید، مشخصات آن را در جدول زیر ثبت نمایید.",
  screening_history: "چنانچه تاکنون در گزینش نهادها، ادارات لشکری یا کشوری، یا مراکز آموزشی دولتی و غیردولتی برای شما پرونده تشکیل شده است، مشخصات آن را در جدول زیر تکمیل نمایید.",
  veteran: "چنانچه خود یا یکی از بستگان شما دارای سابقه ایثارگری، رزمندگی، جانبازی یا سایر سوابق مرتبط هستید، مشخصات و نوع این سابقه را در جدول زیر ثبت نمایید.",
  travel: "چنانچه خود، همسر، بستگان نسبی شما یا همسرتان و در صورت لزوم دوستان و معاشرین شما تاکنون به خارج از کشور مسافرت یا در خارج از کشور اقامت داشته‌اند، مشخصات سفر یا اقامت را در جدول زیر ثبت نمایید.",
  legal_incidents: "چنانچه خود، همسر یا بستگان شما سابقه قضایی یا انتظامی از قبیل احضار، شکایت، بازداشت، دستگیری یا رسیدگی قضایی داشته‌اند، مشخصات آن را در جدول زیر ثبت نمایید.",
  migration: "چنانچه خود، همسر یا بستگان نسبی شما یا همسرتان مهاجر، پناهنده یا بازگشته به جمهوری اسلامی ایران بوده یا هستند، وضعیت مهاجرت، نوع اقامت و سایر مشخصات مربوط را در جدول زیر ثبت نمایید.",
  affiliations: "چنانچه شما، همسر یا بستگان شما با اشخاص حقیقی یا حقوقی، تشکل‌ها، گروه‌ها یا محافل سیاسی و غیرسیاسی در داخل یا خارج از کشور ارتباط، همکاری یا آشنایی داشته‌اند، مشخصات آن را در جدول زیر ثبت نمایید.",
  addiction: "چنانچه خود، همسر یا بستگان نسبی شما سابقه اعتیاد یا مصرف مواد مخدر داشته‌اند، نوع ماده، بازه زمانی و وضعیت فعلی را با دقت در جدول زیر اعلام نمایید.",
  foreign_company_relations: "چنانچه شما، همسر یا اعضای خانواده و بستگان شما با شرکت‌ها و مؤسسات خارجی در داخل کشور همکاری یا اشتغال داشته‌اند یا دارند، مشخصات همکاری یا اشتغال را در جدول زیر تکمیل نمایید.",
  embassy_relations: "چنانچه اعضای خانواده یا بستگان شما یا همسرتان در سفارتخانه‌ها و کنسولگری‌های کشورهای بیگانه شاغل بوده یا هستند یا با آن‌ها ارتباط داشته‌اند، مشخصات مربوط را در جدول زیر درج نمایید.",
  exit_restrictions: "چنانچه خود، همسر، بستگان یا دوستان و معاشرین شما تاکنون ممنوع‌الخروج بوده‌اند، مشخصات مرجع، علت، نتیجه و در صورت وجود، تاریخ رفع ممنوعیت را در جدول زیر ثبت نمایید.",
  activities: "سوابق فعالیت‌های اجتماعی، سیاسی، فرهنگی، جهادی و اقتصادی خود و در صورت لزوم همسر را در جدول زیر ثبت نمایید؛ از جمله فعالیت در بسیج، انجمن‌های اسلامی، کانون‌های فرهنگی و هنری، فعالیت‌های اقتصادی در فضای مجازی یا حقیقی و دفاتر نمایندگی‌های مردمی.",
  weapons: "چنانچه تاکنون سلاحی در اختیار داشته‌اید یا دارید، مشخصات سلاح، مجوز و سایر اطلاعات مرتبط را مطابق واقع در جدول زیر ثبت نمایید.",
  family: "مشخصات پدر، مادر، خواهران و برادران، همسر و فرزندان، اعضای خانواده همسر و نیز پدربزرگ‌ها و مادربزرگ‌ها را طبق جدول تکمیل نمایید. در صورت وجود افراد فوت‌شده در اعضای خانواده، مشخصات آنان را نیز درج کنید.",
  social_relations: "مشخصات افرادی را که شناخت کافی از شما دارند در جدول زیر ثبت نمایید؛ ترجیحاً سه نفر از دوستان دوران تحصیل یا سربازی، چهار نفر از همسایگان و معتمدان محل و دو نفر از بستگانی که شناخت کافی از شما دارند.",
  residence: "نشانی محل‌های سکونت خود را از ده سال گذشته تا کنون، از جدیدترین نشانی به قدیمی‌ترین، به ترتیب ثبت نمایید. آدرس باید دقیق و خوانا بوده و شامل منطقه شهرداری، میدان یا خیابان اصلی، کوچه، پلاک، طبقه و واحد باشد.",
  additional: "چنانچه توضیحات تکمیلی یا سوابق و دستاوردهای علمی، آموزشی، فنی، نظامی یا ورزشی، از جمله المپیاد، نخبگی، مربیگری و موارد مشابه دارید که در بخش‌های قبل درج نشده است، در این قسمت بیان نمایید.",
  declaration: "پس از بررسی نهایی اطلاعات، تعهدنامه را با دقت مطالعه و تأیید نمایید تا پرونده برای ثبت نهایی ارسال شود.",
  documents: "مدارک و مستندات مورد نیاز پرونده را مطابق ضوابط سامانه بارگذاری و بررسی نمایید.",
  review: "پیش از ثبت نهایی، تمامی اطلاعات و سوابق ثبت‌شده را به دقت مرور کرده و در صورت وجود مغایرت، به مرحله مربوطه بازگردید و اصلاح نمایید.",
};

export { STEP_META, RECORDS, FLOW_SECTIONS, STATUS, STEP_DESCRIPTIONS, emptyRecord };
