const STEP_META = {
  personal: { title: "مشخصات فردی", kicker: "هویت و اطلاعات تماس" },
  marriage: { title: "سوابق ازدواج", kicker: "وضعیت خانوادگی" },
  military: { title: "وضعیت نظام وظیفه", kicker: "خدمت و معافیت" },
  education: { title: "سوابق تحصیلی", kicker: "مدارک دانشگاهی و حوزوی" },
  employment: { title: "سوابق شغلی", kicker: "تجربه و محل‌های کار" },
  passport: { title: "گذرنامه", kicker: "سوابق گذرنامه" },
  foreign_contacts: { title: "ارتباطات خارج از کشور", kicker: "ارتباطات و مکاتبات" },
  accommodation: { title: "خوابگاه و پانسیون", kicker: "اقامت‌های دانشجویی و کاری" },
  screening_history: { title: "سوابق گزینش", kicker: "پرونده‌های قبلی" },
  veteran: { title: "سوابق ایثارگری", kicker: "رزمندگی، جانبازی و شهادت" },
  travel: { title: "سفر و اقامت خارج از کشور", kicker: "مسافرت و اقامت" },
  legal_incidents: { title: "سوابق قضایی و انتظامی", kicker: "احضار، بازداشت و دستگیری" },
  migration: { title: "مهاجرت و پناهندگی", kicker: "وضعیت مهاجرت و بازگشت" },
  affiliations: { title: "ارتباط و همکاری", kicker: "اشخاص، تشکل‌ها و گروه‌ها" },
  addiction: { title: "سوابق اعتیاد", kicker: "اطلاعات اعلامی" },
  foreign_company_relations: { title: "شرکت‌ها و مؤسسات خارجی", kicker: "همکاری و اشتغال" },
  embassy_relations: { title: "سفارتخانه و کنسولگری", kicker: "اشتغال و ارتباطات" },
  exit_restrictions: { title: "ممنوع‌الخروجی", kicker: "سوابق و نتایج" },
  activities: { title: "فعالیت‌های اجتماعی و فرهنگی", kicker: "سیاسی، فرهنگی، جهادی و اجتماعی" },
  weapons: { title: "سوابق سلاح", kicker: "سلاح و مجوز" },
  family: { title: "خانواده", kicker: "والدین، خواهر و برادر، همسر و فرزندان" },
  social_relations: { title: "معرفین، دوستان و همسایگان", kicker: "منابع شناخت" },
  residence: { title: "سوابق سکونت ده سال اخیر", kicker: "نشانی‌های محل سکونت" },
  additional: { title: "توضیحات تکمیلی", kicker: "موارد و سوابق تکمیلی" },
  declaration: { title: "تعهد نهایی", kicker: "تأیید و ثبت نهایی پرونده" },
  documents: { title: "مدارک", kicker: "بارگذاری مستندات" },
  review: { title: "مرور نهایی", kicker: "کنترل اطلاعات پیش از ثبت" },
};

const RECORDS = {
  education: [
    { key: "degree_level", label: "مقطع تحصیلی / سطح", type: "text", required: true },
    { key: "institution_name", label: "نام دانشگاه / حوزه", type: "text", required: true },
    { key: "institution_type", label: "نوع دانشگاه", type: "text" },
    { key: "field_of_study", label: "رشته / گرایش", type: "text", required: true },
    { key: "gpa", label: "معدل", type: "number" },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "is_current", label: "در حال تحصیل هستم", type: "boolean" },
    { key: "address_line", label: "نشانی محل تحصیل", type: "textarea", full: true },
    { key: "phone", label: "تلفن محل تحصیل", type: "text" },
  ],
  employment: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "متقاضی" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "organization_name", label: "اداره / محل کار", type: "text", required: true },
    { key: "membership_type", label: "نوع عضویت (رسمی، قراردادی و ...)", type: "text" },
    { key: "position", label: "سمت و شغل", type: "text", required: true },
    { key: "start_date", label: "تاریخ به‌کارگیری", type: "date", required: true },
    { key: "end_date", label: "تاریخ قطع همکاری", type: "date" },
    { key: "termination_reason", label: "علت ترک خدمت (استعفا، بازنشستگی و ...)", type: "textarea", full: true, visibleWhen: (record) => Boolean(record.end_date) },
    { key: "work_address", label: "نشانی محل کار", type: "textarea", full: true },
    { key: "manager_name", label: "نام مسئول", type: "text" },
    { key: "manager_phone", label: "تلفن مسئول", type: "text" },
    { key: "work_phone", label: "تلفن محل کار", type: "text" },
  ],
  passport: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "متقاضی" }, { value: "SPOUSE", label: "همسر" }] },
    {
      key: "passport_type",
      label: "نوع گذرنامه",
      type: "select",
      options: [
        { value: "ordinary", label: "عادی" },
        { value: "service", label: "خدمت" },
        { value: "diplomatic", label: "سیاسی" },
        { value: "other", label: "سایر" },
      ],
      required: true,
    },
    { key: "passport_number", label: "شماره گذرنامه", type: "text", required: true },
    { key: "issue_date", label: "تاریخ صدور", type: "date" },
    { key: "expiry_date", label: "مدت اعتبار", type: "date" },
    { key: "issue_country_id", label: "کشور محل دریافت", type: "country" },
    { key: "issue_province_id", label: "استان محل دریافت", type: "number" },
    { key: "issue_city_id", label: "شهر محل دریافت", type: "number" },
    { key: "notes", label: "ملاحظات", type: "textarea", full: true },
  ],
  foreign_contacts: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "country_name", label: "کشور", type: "text", required: true },
    { key: "entity_name", label: "نام فرد / مؤسسه", type: "text", required: true },
    { key: "contact_type", label: "نوع ارتباط", type: "text", required: true },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "reason", label: "علت و موضوع", type: "textarea", full: true },
    { key: "result", label: "نتیجه ارتباط", type: "textarea", full: true },
    { key: "notes", label: "ملاحظات", type: "textarea", full: true },
  ],
  accommodation: [
    { key: "name", label: "نام خوابگاه / پانسیون", type: "text", required: true },
    { key: "start_date", label: "تاریخ شروع اسکان", type: "date", required: true },
    { key: "end_date", label: "تاریخ پایان اسکان", type: "date" },
    { key: "address_line", label: "آدرس خوابگاه", type: "textarea", full: true },
    { key: "day_manager_name", label: "مسئول روز", type: "text" },
    { key: "day_manager_phone", label: "تلفن مسئول روز", type: "text" },
    { key: "night_manager_name", label: "مسئول شب", type: "text" },
    { key: "night_manager_phone", label: "تلفن مسئول شب", type: "text" },
  ],
  screening_history: [
    { key: "organization_name", label: "نام سازمان / اداره", type: "text", required: true },
    { key: "screening_date", label: "تاریخ گزینش", type: "date" },
    { key: "result", label: "نتیجه گزینش", type: "text", required: true },
    { key: "rejection_reason", label: "علت عدم پذیرش", type: "textarea", full: true, visibleWhen: (record) => /رد|عدم پذیرش|نپذیرفته/.test(record.result || "") },
    { key: "address", label: "نشانی محل گزینش", type: "textarea", full: true },
    { key: "phone", label: "تلفن محل گزینش", type: "text" },
  ],
  veteran: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "veteran_type", label: "نوع ایثارگری", type: "text", required: true },
    { key: "percentage", label: "درصد ایثارگری", type: "number" },
    { key: "occurrence_date", label: "تاریخ وقوع / اعزام", type: "date" },
    { key: "location", label: "محل وقوع / اعزام", type: "text" },
    { key: "issuing_authority", label: "اعزام کننده / مرجع", type: "text" },
    { key: "duration", label: "مدت ایثارگری", type: "text" },
    { key: "notes", label: "توضیحات", type: "textarea", full: true },
  ],
  travel: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "country_id", label: "کشور خارجی", type: "country", required: true },
    { key: "travel_type", label: "نوع مسافرت / اقامت", type: "text", required: true },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "transport_type", label: "نحوه سفر", type: "text" },
    { key: "stay_type", label: "نوع اقامت", type: "text" },
    { key: "stay_place", label: "محل اقامت", type: "textarea", full: true },
    { key: "exit_border", label: "مرز خروجی", type: "text" },
    { key: "passport_number", label: "شماره گذرنامه", type: "text" },
    { key: "reason", label: "علت سفر / اقامت", type: "textarea", full: true },
  ],
  legal_incidents: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "incident_type", label: "نوع سابقه", type: "text", required: true },
    { key: "incident_date", label: "تاریخ", type: "date" },
    { key: "reason", label: "علت", type: "textarea", full: true },
    { key: "location", label: "محل وقوع", type: "text" },
    { key: "authority", label: "مرجع رسیدگی", type: "text" },
    { key: "result", label: "نتیجه رسیدگی", type: "textarea", full: true },
  ],
  migration: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "status", label: "وضعیت", type: "text", required: true },
    { key: "reason", label: "علت مهاجرت / پناهندگی", type: "textarea", full: true },
    { key: "current_status", label: "وضعیت فعلی", type: "textarea", full: true },
    { key: "return_date", label: "تاریخ برگشتن", type: "date" },
    { key: "result", label: "نتیجه", type: "textarea", full: true },
  ],
  affiliations: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "entity_name", label: "نام فرد / شرکت / کشور", type: "text", required: true },
    { key: "country_id", label: "کشور", type: "country" },
    { key: "relation_type", label: "نوع اشتغال / ارتباط / همکاری", type: "text", required: true },
    { key: "activity_title", label: "عنوان فعالیت / مسئولیت", type: "text" },
    { key: "start_date", label: "از تاریخ", type: "date" },
    { key: "end_date", label: "تا تاریخ", type: "date" },
    { key: "reason", label: "علت اشتغال / ارتباط", type: "textarea", full: true },
    { key: "acquaintance_method", label: "زمینه / نحوه آشنایی", type: "textarea", full: true },
    { key: "termination_reason", label: "علت قطع ارتباط", type: "textarea", full: true, visibleWhen: (record) => Boolean(record.end_date) },
  ],
  addiction: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "substance_type", label: "ماده مورد استعمال", type: "text", required: true },
    { key: "start_date", label: "از تاریخ", type: "date" },
    { key: "end_date", label: "تا تاریخ", type: "date" },
    { key: "reason", label: "علت", type: "textarea", full: true },
    { key: "convicted", label: "محکومیت داشته‌ام", type: "boolean" },
    { key: "current_status", label: "وضعیت فعلی", type: "textarea", full: true },
  ],
  foreign_company_relations: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "company_name", label: "نام شرکت / مؤسسه", type: "text", required: true },
    { key: "activity_type", label: "نوع فعالیت", type: "text", required: true },
    { key: "country_id", label: "کشور", type: "country", required: true },
    { key: "income_amount", label: "میزان درآمد", type: "number" },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "dependent_country_id", label: "کشور وابستگی", type: "country" },
    { key: "acquaintance_method", label: "نحوه آشنایی", type: "textarea", full: true },
  ],
  embassy_relations: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "country_id", label: "کشور", type: "country", required: true },
    { key: "relation_type", label: "نوع ارتباط", type: "text", required: true },
    { key: "responsibility", label: "مسئولیت", type: "textarea", full: true },
    { key: "start_date", label: "تاریخ شروع", type: "date" },
    { key: "end_date", label: "تاریخ پایان", type: "date" },
    { key: "address", label: "آدرس", type: "textarea", full: true },
    { key: "phone", label: "تلفن", type: "text" },
  ],
  exit_restrictions: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "reference_date", label: "تاریخ مرجع", type: "date" },
    { key: "authority", label: "مرجع ممنوع‌الخروج کننده", type: "text", required: true },
    { key: "reason", label: "علت", type: "textarea", full: true },
    { key: "result", label: "نتیجه", type: "textarea", full: true },
    { key: "lifted_date", label: "تاریخ رفع ممنوعیت", type: "date" },
  ],
  activities: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "organization_name", label: "نام نهاد / تشکل", type: "text", required: true },
    { key: "activity_type", label: "نوع فعالیت", type: "text", required: true },
    { key: "start_date", label: "از تاریخ", type: "date" },
    { key: "end_date", label: "تا تاریخ", type: "date" },
    { key: "responsibility", label: "نوع مسئولیت / فعالیت", type: "textarea", full: true },
    { key: "motivation", label: "علت / انگیزه فعالیت", type: "textarea", full: true },
    { key: "termination_reason", label: "علت ترک فعالیت", type: "textarea", full: true, visibleWhen: (record) => Boolean(record.end_date) },
    { key: "manager_name", label: "نام مسئول", type: "text" },
    { key: "address", label: "نشانی محل فعالیت", type: "textarea", full: true },
    { key: "phone", label: "تلفن", type: "text" },
  ],
  weapons: [
    { key: "person_role", label: "برای", type: "select", options: [{ value: "APPLICANT", label: "داوطلب" }, { value: "SPOUSE", label: "همسر" }] },
    { key: "weapon_type", label: "نوع سلاح", type: "text", required: true },
    { key: "model", label: "مدل", type: "text" },
    { key: "caliber", label: "کالیبر", type: "text" },
    { key: "body_number", label: "شماره بدنه", type: "text" },
    { key: "manufacturer_country_id", label: "کشور سازنده", type: "country" },
    { key: "license_authority", label: "مرجع صدور مجوز", type: "text" },
    { key: "license_number", label: "شماره مجوز", type: "text" },
    { key: "license_date", label: "تاریخ مجوز", type: "date" },
    { key: "use_reason", label: "علت استفاده", type: "textarea", full: true },
  ],
};

const FLOW_SECTIONS = [
  ["هویت و اطلاعات پایه", ["personal", "marriage", "military"]],
  ["تحصیل و اشتغال", ["education", "employment", "passport"]],
  ["ارتباطات و سوابق", ["foreign_contacts", "screening_history", "veteran", "travel", "legal_incidents", "migration"]],
  ["اقامت و اسکان", ["accommodation"]],
  ["ارتباطات تکمیلی", ["affiliations", "addiction", "foreign_company_relations", "embassy_relations", "exit_restrictions", "activities", "weapons"]],
  ["خانواده و منابع شناخت", ["family", "social_relations", "residence"]],
  ["جمع‌بندی", ["additional", "declaration"]],
];

const STATUS = {
  IN_PROGRESS: ["در حال تکمیل", "progress"],
  RETURNED: ["برگشت داده شده", "returned"],
  SUBMITTED: ["ثبت نهایی شده", "submitted"],
  UNDER_REVIEW: ["در حال بررسی", "review"],
  APPROVED: ["تأیید شده", "approved"],
  REJECTED: ["رد شده", "rejected"],
  COMPLETED: ["تکمیل شده", "approved"],
  DRAFT: ["پیش‌نویس", "muted"],
};


const emptyRecord = (fields) => {
  const out = {};
  fields.forEach((field) => {
    out[field.key] = field.type === "boolean" ? null : "";
  });
  return out;
};

const STEP_DESCRIPTIONS = {
  personal: "اطلاعات هویتی، راه‌های تماس و نشانی‌ها را ثبت کنید.",
  marriage: "هر ازدواج را جداگانه ثبت کنید؛ ازدواج‌های جاری و سوابق ازدواج قبلی می‌توانند هم‌زمان وجود داشته باشند.",
  military: "وضعیت خدمت، سازمان و معافیت را اعلام کنید.",
  education: "سوابق تحصیلی را از آخرین مدرک به قبل ثبت کنید.",
  employment: "سوابق شغلی را از شغل فعلی به قبل وارد کنید.",
  passport: "برای داوطلب و در صورت وجود، همسر، سوابق گذرنامه را ثبت کنید.",
  family: "مشخصات اعضای خانواده را با جزئیات کافی ثبت کنید.",
  social_relations: "افرادی را که شناخت کافی از شما دارند ثبت کنید.",
  residence: "نشانی‌های محل سکونت در ده سال اخیر را به ترتیب ثبت کنید.",
  declaration: "پس از مرور اطلاعات، تعهدنامه را تأیید و پرونده را ثبت نهایی کنید.",
};

export { STEP_META, RECORDS, FLOW_SECTIONS, STATUS, STEP_DESCRIPTIONS, emptyRecord };
